### test my server
GET http://localhost:5000/
content-type: application/json

############# ADD TESTING PRODUCTS ##############
GET http://localhost:5000/api/v1/addTesting
content-type: application/json

### get all courses
GET http://localhost:5000/api/courses

